export default {
        container: {
          backgroundColor: '#343333',
          flex: 1,
        },
        header: {
          backgroundColor: '#979292',
          padding: 10,
          width: '100%',
          height: 155,
          borderRadius: 8,
          alignItems: 'flex-end',
          justifyContent: 'center',
          marginBottom: 10,
          marginTop: '10%',
        },
        history: {
          backgroundColor: '#D9D9D9',
          height: 60,
          width: 300,
          borderRadius: 8,
          justifyContent: 'center',
          alignItems: 'flex-end',
          padding: 10,
          marginBottom: 2,
        },
        result: {
          backgroundColor: '#D9D9D9',
          height: 70,
          width: 390,
          borderRadius: 8,
          justifyContent: 'center',
          alignItems: 'flex-end',
          padding: 10,
          marginTop: 2,
        },
        buttons: {
          backgroundColor: '#979292',
          padding: 5,
          height: '100%',
          borderRadius: 10,
          flexDirection: 'row',
          flexWrap: 'wrap',
        },
        button: {
          backgroundColor: '#3C2CF4',
          flex: 2,
          justifyContent: 'center',
          alignItems: 'center',
          minHeight: 80,
          minWidth: 80,
          borderRadius: 10,
          margin: 5,
        },
        buttonText: {
          color: 'azure',
          fontSize: 30,
        },
        resultText: {
            color: 'black',
            fontSize: 40,
            fontWeight: 'bold',
        },
        historyText: {
            color: 'black',
            fontSize: 25,
            fontWeight: 'bold',
        },
}